# Generated by Django 4.0.3 on 2023-03-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_uploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploaded',
            name='user',
        ),
        migrations.DeleteModel(
            name='Created',
        ),
        migrations.DeleteModel(
            name='Uploaded',
        ),
    ]
